/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_asteriskmods_inputtweaks_rawinput_WindowsNatives */

#ifndef _Included_com_github_asteriskmods_inputtweaks_rawinput_WindowsNatives
#define _Included_com_github_asteriskmods_inputtweaks_rawinput_WindowsNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_asteriskmods_inputtweaks_rawinput_WindowsNatives
 * Method:    setMouseDeltaHandler
 * Signature: (Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_com_github_asteriskmods_inputtweaks_rawinput_WindowsNatives_setMouseDeltaHandler
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_github_asteriskmods_inputtweaks_rawinput_WindowsNatives
 * Method:    registerRawInputDevices
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_asteriskmods_inputtweaks_rawinput_WindowsNatives_registerRawInputDevices
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_asteriskmods_inputtweaks_rawinput_WindowsNatives
 * Method:    rawInputWindowProc
 * Signature: (JIJJ)V
 */
JNIEXPORT void JNICALL Java_com_github_asteriskmods_inputtweaks_rawinput_WindowsNatives_rawInputWindowProc
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
